#!/bin/sh
# Absolute path to this script, e.g. /home/user/bin/foo.sh
SCRIPT=$(readlink -f "$0")
# Absolute path this script is in, thus /home/user/bin
SCRIPTPATH=$(dirname "$SCRIPT")

FILE="$SCRIPTPATH/createObjects-1.0-SNAPSHOT.jar"
if [ ! -f "$FILE" ]; then
    cd .. && gradle createJar
fi

java -jar "$SCRIPTPATH/createObjects-1.0-SNAPSHOT.jar"